main: main.cpp Point3D.cpp Element3D.cpp Line3D.cpp Face3D.cpp
	g++ -o main main.cpp Point3D.cpp Element3D.cpp Line3D.cpp Face3D.cpp
debug: main.cpp Point3D.cpp Element3D.cpp Line3D.cpp Face3D.cpp
	g++ -o debug main.cpp Point3D.cpp Element3D.cpp Line3D.cpp Face3D.cpp -g
	gdb debug
clean:
	rm main debug